#version: '2'
mysqldb: 
    image: mysql5.7:1.0
    container_name: mysqldb
    environment: 
       - MYSQL_ROOT_PASSWORD=gfhl
    ports:
       - "53306:3306"
#    volumes:
#       - /opt/mysql/data:/var/lib/mysql
#       - /opt/mysql/log:/var/log/mysql
